default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bloodbath_dummy_development

test:
  <<: *default
  database: bloodbath_dummy_test

production:
  adapter: postgresql
  secret_key_base: <%= Rails.application.credentials.dig(:secret_key_base) %>
  rails_master_key: <%= ENV['RAILS_MASTER_KEY'] %>
  encoding: unicode
  pool: 5
